#!/usr/bin/env node
// Generate src/data/lastmod-generated.ts mapping tool slug → ISO date
// from the git history of each tool's .astro source file. Imported by
// ToolShell + HealthCalc so each tool page can render "Last updated"
// and emit schema.org dateModified.
//
// Runs via `npm run prebuild` and on demand: `node scripts/gen-lastmod.mjs`.

import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { loadTools, ROOT } from './lib/load-tools.mjs'
import { buildLastModMap } from './lib/git-lastmod.mjs'

const tools = loadTools({ caller: 'gen-lastmod' })

const liveTools = tools.filter(t => t.live)
const today = new Date().toISOString().split('T')[0]
const gitDates = buildLastModMap(ROOT)
const lastmodBySlug = {}

for (const tool of liveTools) {
  lastmodBySlug[tool.slug] = gitDates.get(`src/pages/${tool.slug}.astro`) || today
}

const header = `// Auto-generated by scripts/gen-lastmod.mjs. Do not edit.
// Regenerated on every \`npm run build\`.

export const lastmodBySlug: Record<string, string> = `

const output = header + JSON.stringify(lastmodBySlug, null, 2) + '\n'
const outPath = resolve(ROOT, 'src/data/lastmod-generated.ts')
writeFileSync(outPath, output, 'utf-8')

console.log(`gen-lastmod: wrote ${Object.keys(lastmodBySlug).length} entries → src/data/lastmod-generated.ts`)
