#!/usr/bin/env node
// Generate src/data/lastmod-generated.ts mapping tool slug → ISO date
// from the git history of each tool's .astro source file. Imported by
// ToolShell + HealthCalc so each tool page can render "Last updated"
// and emit schema.org dateModified.
//
// Runs via `npm run prebuild` and on demand: `node scripts/gen-lastmod.mjs`.

import { readFileSync, writeFileSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')

// Reuse tools.ts parsing (same approach as gen-llms.mjs).
const toolsSource = readFileSync(resolve(ROOT, 'src/data/tools.ts'), 'utf-8')
const dataOnly = toolsSource
  .replace(/export interface Tool \{[\s\S]*?\n\}\n/, '')
  .replace(/:\s*Tool\[\]/, '')
  .replace(/^export\s+const\s+tools\s*=/m, 'globalThis.__tools =')

const startIdx = dataOnly.indexOf('globalThis.__tools =')
if (startIdx === -1) {
  console.error('gen-lastmod: could not locate tools array')
  process.exit(1)
}
const bracketStart = dataOnly.indexOf('[', startIdx)
let depth = 0
let bracketEnd = -1
for (let i = bracketStart; i < dataOnly.length; i++) {
  const ch = dataOnly[i]
  if (ch === '[') depth++
  else if (ch === ']') {
    depth--
    if (depth === 0) { bracketEnd = i; break }
  }
}
const arrayLiteral = dataOnly.slice(bracketStart, bracketEnd + 1)
const tools = (0, eval)(`(${arrayLiteral})`)

const liveTools = tools.filter(t => t.live)
const today = new Date().toISOString().split('T')[0]
const lastmodBySlug = {}

for (const tool of liveTools) {
  const file = `src/pages/${tool.slug}.astro`
  try {
    const out = execSync(`git log -1 --format=%aI -- "${file}"`, {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'ignore'],
      cwd: ROOT,
    }).trim()
    lastmodBySlug[tool.slug] = out ? out.split('T')[0] : today
  } catch {
    lastmodBySlug[tool.slug] = today
  }
}

const header = `// Auto-generated by scripts/gen-lastmod.mjs. Do not edit.
// Regenerated on every \`npm run build\`.

export const lastmodBySlug: Record<string, string> = `

const output = header + JSON.stringify(lastmodBySlug, null, 2) + '\n'
const outPath = resolve(ROOT, 'src/data/lastmod-generated.ts')
writeFileSync(outPath, output, 'utf-8')

console.log(`gen-lastmod: wrote ${Object.keys(lastmodBySlug).length} entries → src/data/lastmod-generated.ts`)
