/**
 * @vitest-environment jsdom
 */
import { describe, test, expect, afterEach, vi } from 'vitest'
import { readFileSync } from 'fs'
import { resolve } from 'path'

const ROOT = resolve(import.meta.dirname, '..')
const read = p => readFileSync(resolve(ROOT, p), 'utf-8')
const astro = read('src/components/CommandPalette.astro')
const js = read('src/tools/command-palette.js')

// The real, committed exercise index (public/exercises/browse-index.json is
// source-controlled, generated by scripts/gen-exercises.mjs — not gitignored
// like palette-tools.json). Using the real data here is deliberate: the
// "barbell hits 95 by name but 215+ once equipment counts" style claims in
// this feature's spec are about real vocabulary (real muscles, real
// equipment, real exercise names), and a 5-row synthetic fixture can't
// reproduce that. palette-tools.json IS gitignored (prebuild output), so
// tool data below is a small hand-built fixture instead.
const REAL_EXERCISES = JSON.parse(read('public/exercises/browse-index.json'))

const TOOLS = [
  { slug: 'json-formatter', name: 'JSON Formatter', emoji: '🧾', category: 'Developer', subcategory: 'Data', keywords: ['json', 'format', 'pretty print'], description: 'Format and validate JSON.' },
  { slug: 'qr-code-generator', name: 'QR Code Generator', emoji: '🔳', category: 'Generator', subcategory: 'Image', keywords: ['qr', 'barcode'], description: 'Generate a QR code from text or a URL.' },
  { slug: 'barbell-plate-calculator', name: 'Barbell Plate Calculator', emoji: '🏋️', category: 'Fitness', subcategory: 'Calculators', keywords: ['barbell', 'plates', 'weight'], description: 'Work out which plates to load for a target barbell weight.' },
]

function mountDom() {
  document.body.innerHTML = `
    <div id="cmd-overlay" class="cmd-overlay" hidden role="dialog">
      <div id="cmd-backdrop" class="cmd-backdrop"></div>
      <div class="cmd-panel">
        <input type="search" id="cmd-input" class="cmd-input" />
        <div id="cmd-results" class="cmd-results"></div>
      </div>
    </div>
  `
}

function stubFetch(toolsData, exercisesData) {
  vi.stubGlobal('fetch', (url) => {
    const u = String(url)
    if (u.indexOf('palette-tools.json') !== -1) {
      return Promise.resolve({ ok: true, json: () => Promise.resolve(toolsData) })
    }
    if (u.indexOf('browse-index.json') !== -1) {
      return Promise.resolve({ ok: true, json: () => Promise.resolve(exercisesData) })
    }
    return Promise.resolve({ ok: false, json: () => Promise.resolve([]) })
  })
}

function stubFailedExercises(toolsData) {
  vi.stubGlobal('fetch', (url) => {
    const u = String(url)
    if (u.indexOf('palette-tools.json') !== -1) {
      return Promise.resolve({ ok: true, json: () => Promise.resolve(toolsData) })
    }
    return Promise.reject(new Error('offline'))
  })
}

async function loadScriptFresh() {
  // The script self-initializes at import time (reads the DOM, wires
  // listeners), so a cached module would silently no-op on re-import.
  vi.resetModules()
  await import('./tools/command-palette.js')
}

async function flush() {
  await new Promise(r => setTimeout(r, 0))
  await new Promise(r => setTimeout(r, 0))
  await new Promise(r => setTimeout(r, 0))
}

// Longer than the script's 100ms input debounce.
const afterDebounce = () => new Promise(r => setTimeout(r, 150))

function rowNames() {
  return [...document.querySelectorAll('#cmd-results .cmd-row .cmd-row-name')].map(n => n.textContent)
}

function exerciseRows() {
  return [...document.querySelectorAll('#cmd-results a.cmd-row[href^="/exercises/"]:not(.cmd-row-more)')]
}

function typeQuery(q) {
  const input = document.getElementById('cmd-input')
  input.value = q
  input.dispatchEvent(new Event('input', { bubbles: true }))
}

async function openAndSearch(q, toolsData = TOOLS, exercisesData = REAL_EXERCISES) {
  mountDom()
  stubFetch(toolsData, exercisesData)
  await loadScriptFresh()
  window.maratoolOpenCmdPalette()
  await flush()
  typeQuery(q)
  await afterDebounce()
}

afterEach(() => {
  vi.unstubAllGlobals()
  document.body.innerHTML = ''
})

describe('CommandPalette.astro — contract', () => {
  test('behaviour lives in a non-module tool script (type="module" 404s in prod)', () => {
    expect(astro).toContain('<script src="../tools/command-palette.js">')
    expect(astro).not.toMatch(/type="module"/)
  })
})

describe('command-palette.js — source contract', () => {
  test('uses the hidden attribute rather than style.display', () => {
    expect(js).not.toMatch(/style\.display/)
  })

  test('exercise rows link to /exercises/{slug}/ with a trailing slash', () => {
    expect(js).toContain('href="/exercises/\' + ex.slug + \'/"')
  })

  test('contains no hardcoded misspelling — typo tolerance must be a general algorithm, not a word list', () => {
    // The owner's screenshot happened to say "Harmstring"; the fix is a
    // general edit-distance matcher, not a fix for that one word. A grep hit
    // here (outside this comment) would mean someone special-cased it.
    expect(js.toLowerCase().replace(/\/\/.*$|\/\*[\s\S]*?\*\//gm, '')).not.toContain('harmstring')
  })

  test('implements Damerau-Levenshtein (has a transposition branch), not plain Levenshtein', () => {
    expect(js).toMatch(/function damerauLevenshtein/)
    // The transposition branch compares a[i-1]/b[j-2] and a[i-2]/b[j-1] —
    // the swap check that plain Levenshtein DP tables don't have.
    expect(js).toMatch(/a\.charAt\(i - 1\) === b\.charAt\(j - 2\)/)
  })

  test('scales the typo threshold to word length instead of a single fixed distance', () => {
    expect(js).toMatch(/function typoThreshold/)
    expect(js).toMatch(/len < 4/)
  })

  test('fuzzy matching only runs after an exact search on both pools misses', () => {
    expect(js).toMatch(/fuzzySearchExercises\(q\)/)
    // The call site is gated behind "both empty", not run unconditionally.
    expect(js).toMatch(/toolHits\.length === 0 && exerciseHits\.length === 0/)
  })
})

describe('command-palette.js — exercise search (behavioural, real data)', () => {
  test('finds exercise results for "barbell"', async () => {
    await openAndSearch('barbell')
    expect(exerciseRows().length).toBeGreaterThan(0)
    expect(document.getElementById('cmd-results').textContent).toContain('Exercises')
  })

  test('finds exercise results for "air bike"', async () => {
    await openAndSearch('air bike')
    expect(exerciseRows().length).toBeGreaterThan(0)
    expect(rowNames().some(n => /air bike/i.test(n))).toBe(true)
  })

  test('finds exercise results for "hamstring"', async () => {
    await openAndSearch('hamstring')
    expect(exerciseRows().length).toBeGreaterThan(0)
  })

  test('matching primaryMuscles and equipment (not just name) surfaces far more matches — "barbell" hits ~95 by name alone but 200+ once equipment counts', async () => {
    await openAndSearch('barbell')
    const seeAll = document.querySelector('.cmd-row-more')
    expect(seeAll).not.toBeNull()
    const total = parseInt(seeAll.textContent.match(/(\d+)/)[1], 10)
    expect(total).toBeGreaterThan(150)
  })

  test('matching primaryMuscles surfaces far more matches — "hamstring" hits 12 by name alone but 80+ once muscles count', async () => {
    await openAndSearch('hamstring')
    const seeAll = document.querySelector('.cmd-row-more')
    expect(seeAll).not.toBeNull()
    const total = parseInt(seeAll.textContent.match(/(\d+)/)[1], 10)
    expect(total).toBeGreaterThan(50)
  })

  test('caps rendered exercise rows and shows a "see all" row with the true total, rather than truncating silently', async () => {
    await openAndSearch('barbell')
    expect(exerciseRows().length).toBeLessThanOrEqual(20)
    const seeAll = document.querySelector('.cmd-row-more')
    expect(seeAll).not.toBeNull()
    expect(seeAll.getAttribute('href')).toBe('/exercises/?q=barbell')
    expect(seeAll.textContent).toMatch(/see all \d+/i)
  })

  test('every exercise row links to /exercises/{slug}/ with a trailing slash', async () => {
    await openAndSearch('barbell')
    const hrefs = exerciseRows().map(a => a.getAttribute('href'))
    expect(hrefs.length).toBeGreaterThan(0)
    for (const h of hrefs) {
      expect(h.startsWith('/exercises/')).toBe(true)
      expect(h.endsWith('/')).toBe(true)
    }
  })
})

describe('command-palette.js — typo tolerance (behavioural, general — not one word)', () => {
  test('insertion: "harmstring" finds hamstring exercises via the fuzzy fallback', async () => {
    await openAndSearch('harmstring')
    expect(exerciseRows().length).toBeGreaterThan(0)
    expect(document.getElementById('cmd-results').textContent).toMatch(/close match/i)
  })

  test('transposition: "sqaut" finds squat exercises — plain Levenshtein (distance 2) would miss this at a distance-1 threshold', async () => {
    await openAndSearch('sqaut')
    expect(exerciseRows().length).toBeGreaterThan(0)
    expect(rowNames().some(n => /squat/i.test(n))).toBe(true)
    expect(document.getElementById('cmd-results').textContent).toMatch(/close match/i)
  })

  test('deletion: "dumbell" finds dumbbell-equipment exercises', async () => {
    await openAndSearch('dumbell')
    expect(exerciseRows().length).toBeGreaterThan(0)
    expect(document.getElementById('cmd-results').textContent).toMatch(/close match/i)
  })

  test('deletion: "tricep" finds triceps exercises', async () => {
    await openAndSearch('tricep')
    // "tricep" happens to already be a substring of "triceps", so this may
    // be satisfied by the exact facet match rather than the fuzzy fallback —
    // either way, real results must come back.
    expect(exerciseRows().length).toBeGreaterThan(0)
  })

  test('transposition: "bicpes" finds biceps exercises', async () => {
    await openAndSearch('bicpes')
    expect(exerciseRows().length).toBeGreaterThan(0)
    expect(document.getElementById('cmd-results').textContent).toMatch(/close match/i)
  })

  test('negative: "zzzzqqq" returns nothing, even with the fuzzy fallback active', async () => {
    await openAndSearch('zzzzqqq')
    expect(exerciseRows().length).toBe(0)
    expect(document.getElementById('cmd-results').textContent.toLowerCase()).toContain('no tools or exercises found')
  })
})

describe('command-palette.js — tools vs exercises (behavioural)', () => {
  test('tool hits still appear and their row precedes every exercise row in the DOM', async () => {
    await openAndSearch('barbell') // matches the Barbell Plate Calculator tool AND many exercises
    const results = document.getElementById('cmd-results')
    const allRows = [...results.querySelectorAll('.cmd-row')]
    const firstToolIdx = allRows.findIndex(r => r.getAttribute('href') === '/barbell-plate-calculator/')
    const firstExerciseIdx = allRows.findIndex(r => (r.getAttribute('href') || '').indexOf('/exercises/') === 0)
    expect(firstToolIdx).toBeGreaterThanOrEqual(0)
    expect(firstExerciseIdx).toBeGreaterThan(firstToolIdx)
  })

  test('a failed exercises fetch leaves tool search working', async () => {
    mountDom()
    stubFailedExercises(TOOLS)
    await loadScriptFresh()
    window.maratoolOpenCmdPalette()
    await flush()
    typeQuery('json')
    await afterDebounce()

    expect(rowNames()).toContain('JSON Formatter')
    expect(document.getElementById('cmd-results').textContent).not.toMatch(/exercises/i)
  })

  test('updates the empty state to mention both tools and exercises, not just tools', async () => {
    await openAndSearch('nomatchatallxyz')
    expect(document.getElementById('cmd-results').textContent.toLowerCase()).toContain('no tools or exercises found')
  })
})

describe('command-palette.js — keyboard behaviour across both groups', () => {
  test('ArrowDown moves the active row across the group boundary, into the exercises group', async () => {
    await openAndSearch('barbell')
    const input = document.getElementById('cmd-input')
    const rows = () => [...document.querySelectorAll('#cmd-results .cmd-row')]
    expect(rows()[0].classList.contains('active')).toBe(true)
    const total = rows().length
    for (let i = 0; i < total - 1; i++) {
      input.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true }))
    }
    expect(rows()[total - 1].classList.contains('active')).toBe(true)
    expect(rows()[0].classList.contains('active')).toBe(false)
  })

  test('Cmd+Enter opens the active row in a new tab', async () => {
    await openAndSearch('barbell')
    const openSpy = vi.fn()
    vi.stubGlobal('open', openSpy)
    document.getElementById('cmd-input').dispatchEvent(
      new KeyboardEvent('keydown', { key: 'Enter', metaKey: true, bubbles: true })
    )
    expect(openSpy).toHaveBeenCalledWith('/barbell-plate-calculator/', '_blank')
  })

  test('Escape closes the palette', async () => {
    await openAndSearch('barbell')
    const overlay = document.getElementById('cmd-overlay')
    expect(overlay.hidden).toBe(false)
    document.getElementById('cmd-input').dispatchEvent(
      new KeyboardEvent('keydown', { key: 'Escape', bubbles: true })
    )
    expect(overlay.hidden).toBe(true)
  })
})
